project:
  type: website
  
website:
  title: "Fisika"
  site-url: fisika-lovat.vercel.app
  page-navigation: true
  description: "sebuah website untuk sumber terbuka pembelajaran fisika"
  page-footer:
    left: 
      Powered by
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)
    center:
      - text: "License"
        href: license.qmd

    right:
      - icon: https://raw.githubusercontent.com/misskey-dev/assets/main/icon.png
        href: https://twitter.com/quarto_pub
        aria-label: Quarto Twitter
      - icon: github
        href: https://github.com/LLENN8/Fisika
        aria-label: Quarto GitHub
  sidebar:
    style: "docked"  
    contents:
      - section: "Pengantar"
        contents:
          - text: "Selamat Datang"
            file: index.qmd
          - text: "Tentang Penulis"
            file: tentang-penulis.qmd
      - section: "Pengukuran"
        contents:
          - text: "Pengukuran Fisika"
            file: Pengukuran-Fisika.qmd
          - text: "Alat-ukur"
            file: Alat-ukur.qmd
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true