project:
  type: website
  
website:
  title: "Fisika"
  repo-url: https://github.com/LLENN8/Fisika
  repo-actions: [issue]

  site-url: https://misaka-fisika.vercel.app
  page-navigation: true
  description: "sebuah website untuk sumber terbuka pembelajaran fisika"
  page-footer:
    left: 
      Powered by
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)
    center:
      - text: "License"
        href: https://github.com/LLENN8/Fisika/blob/master/LICENSE

    right:
      - icon: https://raw.githubusercontent.com/misskey-dev/assets/main/icon.png
        href: https://twitter.com/quarto_pub
        aria-label: Quarto Twitter
      - icon: github
        href: https://github.com/LLENN8/Fisika
        aria-label: Quarto GitHub
  sidebar:
    style: "docked"
    tools:
      - icon: brightness-high-fill  
    contents:
      - section: "Pengantar"
        contents:
          - text: "Selamat Datang"
            file: main/index.qmd
          - text: "Tentang Penulis"
            file: main/tentang-penulis.qmd
      - section: "1. Pengukuran"
        contents:
          - text: "Pengukuran Fisika"
            file: main/pengukuran-fisika.qmd

    

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true